FROM ruby:4.0.7-slim-bookworm AS base
RUN apt update && apt install -y --no-install-recommends openssh-client ca-certificates
RUN gem install build-labels:0.0.85 dry-stack:0.1.60
RUN install-docker-static # 29

WORKDIR /build
RUN mkdir -p /root/.ssh && mkdir -pv /root/.ssh/sockets
RUN printf 'Host *\n\tControlPersist yes\n\tControlMaster auto\n\tControlPath  /root/.ssh/sockets/%%r@%%h-%%p\n\tBatchMode yes\n\tStrictHostKeyChecking no\n\tPort 22\n' > /root/.ssh/config
ADD . .

CMD ["sh", "-c", "rparallel <<EOF \n\
    cat otlp.drs stack.drs  | dry-stack swarm_deploy --tls-domain=example.com -x ssh://example.com -- --prune \n\
EOF\n"]
